# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reddit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reddit
  
  pod 'Alamofire', '~> 5.5'

  target 'redditTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'redditUITests' do
    # Pods for testing
  end

end
